image: mcr.microsoft.com/dotnet/core/sdk:3.1

pipelines:
    default:
        -   step:
                caches:
                    - dotnetcore
                script:
                    - dotnet restore
                    - dotnet build src/GithubStatistics.WebAPI
                    - dotnet test test/GithubStatistics.Application.UnitTest
                    - dotnet test test/GithubStatistics.WebAPI.IntegrationTest
